name: test_github_actions_workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test job
      run: echo "this is sample job"
      shell: bash
