name: test_github_actions_workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  testjob:
    runs-on: ubuntu-latest
    steps:
    - uses: wakaleo/game-of-life@master
    - name: test job
      run: mvn compile
      shell: bash
